# Generated by Django 5.2.5 on 2025-09-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
